[package]
name = "npuzzle"
version = "0.1.0"
authors = ["flevesqu <flevesqu@student.42.fr>", "chacha <nkrouglo@student.42.fr>"]

[dependencies]
regex = "0.2"
ansi_term = "0.9"

piston = "0.36.0"
pistoncore-glutin_window = "0.46.0"
piston2d-opengl_graphics = "0.53.0"
piston2d-graphics = "0.26.0"
